---
deployment:
  tasks:
    - export DEPLOYPATH=/home/gazivkve/ummahaidsociety.com/
    - /bin/cp -r * $DEPLOYPATH #copy all from root
#    - /bin/cp -r ./public/* $DEPLOYPATH/public_html/
    - /bin/cp ./public/js/*.js $DEPLOYPATH/ummahaidsociety.com/js
    - /bin/cp ./public/css/*.css $DEPLOYPATH/ummahaidsociety.com/css